# api_url for GDMS
api_url: https://gdms.cwa.gov.tw/php

# log_level ERROR > WARNING > INFO > DEBUG
log_level: DEBUG

eq_condition: {
    "output": 'multi-mseed',
    "network": 'TSMIP',
    "station": 'all',
    'channel': "HL?",
    "location": "all",
    "dt1": -120,
    "dt2": 480,
		'timelist': "2023-07-15T07:50:51\n2023-07-16T10:22:28\n2023-07-18T08:29:40\n2023-07-19T07:14:30\n2023-07-27T02:42:55\n2023-07-28T01:17:54\n2023-07-30T04:44:35\n2023-07-30T02:13:26\n2023-07-31T04:38:56",
    "label": "Test_function"
}

catalog_range: {
    "stdate": '2018-01-01',
    "eddate": '2023-08-30',
    "stML": '0',
    "edML": '10',
    "sttime": '00:00:00',
    "edtime": '00:00:00',
    "stdep": '0',
    "eddep": '1000',
    "stlon": '118',
    "edlon": '126',
    "stlat": '20',
    "edlat": '26'
}