# api_url for GDMS
GDMS_api_url: https://gdms.cwa.gov.tw
GCMT_api_url: https://www.globalcmt.org
download_path: E:\\Yu\\eFlatfile\\TSMIP_Dataset

# log_level ERROR > WARNING > INFO > DEBUG
log_level: DEBUG

# yr mo day 起始年月日
# oyr omo oday 結束年月日
# llat ulat llon ulon lhd uhd 經緯深範圍
# 其餘參數參閱 https://www.globalcmt.org/CMTsearch.html
gcmt_catalog_range: {
    "itype": "ymd",
    "yr": "2020",
    "mo": "1",
    "day": "1",
    "otype": "ymd",
    "oyr": "2023",
    "omo": "9",
    "oday": "1",
    "jyr": "1976",
    "jday": "1",
    "ojyr": "1976",
    "ojday": "1",
    "nday": "1",
    "lmw": "0",
    "umw": "10",
    "lms": "0",
    "ums": "10",
    "lmb": "0",
    "umb": "10",
    "llat": "21.5",
    "ulat": "26",
    "llon": "119",
    "ulon": "123",
    "lhd": "0",
    "uhd": "1000",
    "lts": "-9999",
    "uts": "9999",
    "lpe1": "0",
    "upe1": "90",
    "lpe2": "0",
    "upe2": "90",
    "list": "0"
}
eq_condition: {
    "output": 'multi-mseed',
    "network": 'TSMIP',
    "station": 'all',
    'channel': "HL?",
    "location": "all",
    "dt1": -120,
    "dt2": 480,
		'timelist': "2022-09-18T14:44:15",
    "label": "Test_function_"
}

catalog_range: {
    "stdate": '2014-01-01',
    "eddate": '2023-08-30',
    "stML": '0',
    "edML": '10',
    "sttime": '00:00:00',
    "edtime": '00:00:00',
    "stdep": '0',
    "eddep": '1000',
    "stlon": '118',
    "edlon": '126',
    "stlat": '20',
    "edlat": '26'
}

instrument_response: {
  "output": "pz2",
  "network": "TSMIP",
  "station": "all",
  "channel": "HL?",
  "location": "all",
  "stDatetime": "2020-12-01",
  "edDatetime": "2023-09-21",
  "label": "All"
}
