# api_url for GDMS
api_url: https://gdms.cwa.gov.tw
download_path: E:\\Yu\\eFlatfile\\TSMIP_Dataset


# log_level ERROR > WARNING > INFO > DEBUG
log_level: DEBUG

eq_condition: {
    "output": 'multi-mseed',
    "network": 'TSMIP',
    "station": 'all',
    'channel': "HL?",
    "location": "all",
    "dt1": -120,
    "dt2": 480,
    "timelist": '2023-07-31T04:38:56',
    "label": "Test_function"
}

catalog_range: {
    "stdate": '2023-01-01',
    "eddate": '2023-08-30',
    "stML": '0',
    "edML": '10',
    "sttime": '00:00:00',
    "edtime": '00:00:00',
    "stdep": '0',
    "eddep": '1000',
    "stlon": '118',
    "edlon": '126',
    "stlat": '20',
    "edlat": '26'
}

instrument_response: {
    "output": "pz2",
    "network": "TSMIP",
    "station": "A002, A003,",
    "channel": "HL?",
    "location": "all",
    "stDatetime": "2023-09-20",
    "edDatetime": "2023-09-21",
    "label": "response"
}