# api_url for GDMS
GDMS_api_url: https://gdms.cwa.gov.tw
GCMT_api_url: https://www.ldeo.columbia.edu/~gcmt/projects/CMT/catalog/NEW_MONTHLY
download_path: E:\\Yu\\eFlatfile\\TSMIP_Dataset

# log_level ERROR > WARNING > INFO > DEBUG
log_level: DEBUG

eq_condition: {
    "output": 'multi-mseed',
    "network": 'TSMIP',
    "station": 'all',
    'channel': "HL?",
    "location": "all",
    "dt1": -120,
    "dt2": 480,
		'timelist': "2022-09-18T14:44:15",
    "label": "Test_function_"
}

catalog_range: {
    "stdate": '2014-01-01',
    "eddate": '2023-08-30',
    "stML": '0',
    "edML": '10',
    "sttime": '00:00:00',
    "edtime": '00:00:00',
    "stdep": '0',
    "eddep": '1000',
    "stlon": '118',
    "edlon": '126',
    "stlat": '20',
    "edlat": '26'
}

instrument_response: {
  "output": "pz2",
  "network": "TSMIP",
  "station": "all",
  "channel": "HL?",
  "location": "all",
  "stDatetime": "2020-12-01",
  "edDatetime": "2023-09-21",
  "label": "All"
}
