version: '3'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: edream2023
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  python_sac:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - DISPLAY=140.115.78.186:0.0
    volumes:
      - ./TSMIP_Dataset:/app/TSMIP_Dataset
    depends_on:
      - mariadb
  r:
    image: r-base
    ports:
      - "7000:7000"
    environment:
      - DISPLAY=140.115.78.186:0.0
    depends_on:
      - mariadb
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb
