version: '3'
services:
  python_sac:
    build: 
      context: .
      dockerfile: dockerfile.python_sac
    ports:
      - "8000:7000"
    environment:
      - DISPLAY=140.115.78.186:0.0
    volumes:
      - ./TSMIP_Dataset:/app/TSMIP_Dataset
    stdin_open: true
    tty: true

  r:
    build: 
      context: .
      dockerfile: dockerfile.r
    ports:
      - "7001:7000"
    environment:
      - DISPLAY=140.115.78.186:0.0
    volumes:
      - ./TSMIP_Dataset:/app/TSMIP_Dataset
      - ./filter:/app/filter
    stdin_open: true
    tty: true