# ¼g¤J¸ê®Æ®w
# SGM_SN<-"S001391"

Write_to_DB <- function(file_id,pfile,file_name,icomp,nroll,HP,LP,PGA,PGV,PGD,rsp,author,md5){
#con <- dbConnect(dbDriver("MySQL"), host=mysql.ip, username=mysql.username, password=mysql.password, dbname=mysql.dbname)
rs <- dbSendQuery(con, statement = paste(
                      "INSERT into SGM (`file_id`,`pfile`,`file_name`,`icomp`,`nroll`,`HP`,`LP`,`PGA`,`PGV`,`PGD`,`T0_010S`,`T0_020S`,`T0_022S`,`T0_025S`,
                      `T0_029S`,`T0_030S`,`T0_032S`,`T0_035S`,`T0_036S`,`T0_040S`,`T0_042S`,`T0_044S`,`T0_045S`,`T0_046S`,`T0_048S`,`T0_050S`,
                      `T0_055S`,`T0_060S`,`T0_065S`,`T0_067S`,`T0_070S`,`T0_075S`,`T0_080S`,`T0_085S`,`T0_090S`,`T0_095S`,`T0_100S`,`T0_110S`,
                      `T0_120S`,`T0_130S`,`T0_133S`,`T0_140S`,`T0_150S`,`T0_160S`,`T0_170S`,`T0_180S`,`T0_190S`,`T0_200S`,`T0_220S`,`T0_240S`,
                      `T0_250S`,`T0_260S`,`T0_280S`,`T0_290S`,`T0_300S`,`T0_320S`,`T0_340S`,`T0_350S`,`T0_360S`,`T0_380S`,`T0_400S`,`T0_420S`,
                      `T0_440S`,`T0_450S`,`T0_460S`,`T0_480S`,`T0_500S`,`T0_550S`,`T0_600S`,`T0_650S`,`T0_667S`,`T0_700S`,`T0_750S`,`T0_800S`,
                      `T0_850S`,`T0_900S`,`T0_950S`,`T1_000S`,`T1_100S`,`T1_200S`,`T1_300S`,`T1_400S`,`T1_500S`,`T1_600S`,`T1_700S`,`T1_800S`,
                      `T1_900S`,`T2_000S`,`T2_200S`,`T2_400S`,`T2_500S`,`T2_600S`,`T2_800S`,`T3_000S`,`T3_200S`,`T3_400S`,`T3_500S`,`T3_600S`,
                      `T3_800S`,`T4_000S`,`T4_200S`,`T4_400S`,`T4_600S`,`T4_800S`,`T5_000S`,`T5_500S`,`T6_000S`,`T6_500S`,`T7_000S`,`T7_500S`,
                      `T8_000S`,`T8_500S`,`T9_000S`,`T9_500S`,`T10_000S`, `author`, `md5_check`) values('",
                      file_id,"','",
                      pfile,"','",
                      file_name,"','",
                      icomp ,"','",
                      nroll ,"','",
                      HP ,"','",
                      LP ,"','",
                      PGA ,"','",
                      PGV ,"','",
                      PGD ,"','",
                      rsp[1  ] ,"','",
                      rsp[2  ] ,"','",
                      rsp[3  ] ,"','",
                      rsp[4  ] ,"','",
                      rsp[5  ] ,"','",
                      rsp[6  ] ,"','",
                      rsp[7  ] ,"','",
                      rsp[8  ] ,"','",
                      rsp[9  ] ,"','",
                      rsp[10 ] ,"','",
                      rsp[11 ] ,"','",
                      rsp[12 ] ,"','",
                      rsp[13 ] ,"','",
                      rsp[14 ] ,"','",
                      rsp[15 ] ,"','",
                      rsp[16 ] ,"','",
                      rsp[17 ] ,"','",
                      rsp[18 ] ,"','",
                      rsp[19 ] ,"','",
                      rsp[20 ] ,"','",
                      rsp[21 ] ,"','",
                      rsp[22 ] ,"','",
                      rsp[23 ] ,"','",
                      rsp[24 ] ,"','",
                      rsp[25 ] ,"','",
                      rsp[26 ] ,"','",
                      rsp[27 ] ,"','",
                      rsp[28 ] ,"','",
                      rsp[29 ] ,"','",
                      rsp[30 ] ,"','",
                      rsp[31 ] ,"','",
                      rsp[32 ] ,"','",
                      rsp[33 ] ,"','",
                      rsp[34 ] ,"','",
                      rsp[35 ] ,"','",
                      rsp[36 ] ,"','",
                      rsp[37 ] ,"','",
                      rsp[38 ] ,"','",
                      rsp[39 ] ,"','",
                      rsp[40 ] ,"','",
                      rsp[41 ] ,"','",
                      rsp[42 ] ,"','",
                      rsp[43 ] ,"','",
                      rsp[44 ] ,"','",
                      rsp[45 ] ,"','",
                      rsp[46 ] ,"','",
                      rsp[47 ] ,"','",
                      rsp[48 ] ,"','",
                      rsp[49 ] ,"','",
                      rsp[50 ] ,"','",
                      rsp[51 ] ,"','",
                      rsp[52 ] ,"','",
                      rsp[53 ] ,"','",
                      rsp[54 ] ,"','",
                      rsp[55 ] ,"','",
                      rsp[56 ] ,"','",
                      rsp[57 ] ,"','",
                      rsp[58 ] ,"','",
                      rsp[59 ] ,"','",
                      rsp[60 ] ,"','",
                      rsp[61 ] ,"','",
                      rsp[62 ] ,"','",
                      rsp[63 ] ,"','",
                      rsp[64 ] ,"','",
                      rsp[65 ] ,"','",
                      rsp[66 ] ,"','",
                      rsp[67 ] ,"','",
                      rsp[68 ] ,"','",
                      rsp[69 ] ,"','",
                      rsp[70 ] ,"','",
                      rsp[71 ] ,"','",
                      rsp[72 ] ,"','",
                      rsp[73 ] ,"','",
                      rsp[74 ] ,"','",
                      rsp[75 ] ,"','",
                      rsp[76 ] ,"','",
                      rsp[77 ] ,"','",
                      rsp[78 ] ,"','",
                      rsp[79 ] ,"','",
                      rsp[80 ] ,"','",
                      rsp[81 ] ,"','",
                      rsp[82 ] ,"','",
                      rsp[83 ] ,"','",
                      rsp[84 ] ,"','",
                      rsp[85 ] ,"','",
                      rsp[86 ] ,"','",
                      rsp[87 ] ,"','",
                      rsp[88 ] ,"','",
                      rsp[89 ] ,"','",
                      rsp[90 ] ,"','",
                      rsp[91 ] ,"','",
                      rsp[92 ] ,"','",
                      rsp[93 ] ,"','",
                      rsp[94 ] ,"','",
                      rsp[95 ] ,"','",
                      rsp[96 ] ,"','",
                      rsp[97 ] ,"','",
                      rsp[98 ] ,"','",
                      rsp[99 ] ,"','",
                      rsp[100] ,"','",
                      rsp[101] ,"','",
                      rsp[102] ,"','",
                      rsp[103] ,"','",
                      rsp[104] ,"','",
                      rsp[105] ,"','",
                      author   ,"','",
                      md5 ,"')", sep=""
                      ))
dbDisconnect(con)
}

Write_to_DB_sort <- function(file_id,pfile,file_name,icomp,nroll,HP,LP,PGA,PGV,PGD,author,md5){
con <- dbConnect(dbDriver("MySQL"), host=mysql.ip, username=mysql.username, password=mysql.password, dbname=mysql.dbname)
rs <- dbSendQuery(con, statement = paste(
                      "INSERT into SGM (`file_id`,`pfile`,`file_name`,`icomp`,`nroll`,`HP`,`LP`,`PGA`,`PGV`,`PGD`, `author`, `md5_check`) values('",
                      file_id,"','",
                      pfile,"','",
                      file_name,"','",
                      icomp ,"','",
                      nroll ,"','",
                      HP ,"','",
                      LP ,"','",
                      PGA ,"','",
                      PGV ,"','",
                      PGD ,"','",
                      author   ,"','",
                      md5 ,"')", sep=""
                      ))
dbDisconnect(con)
}



Write_ACC_to_DB <- function(file_id,pfile,file_name,dt,npts, md5, author){
con <- dbConnect(dbDriver("MySQL"), host=mysql.ip, username=mysql.username, password=mysql.password, dbname=mysql.dbname)
rs <- dbSendQuery(con, statement = paste(
                      "INSERT into sgm_data_processed (`file_id`,`pfile`,`file_name`,`DT`,`NP`,`md5_check`, `author`) values('",
                      file_id,"','",
                      pfile,"','",
                      file_name,"','",
                      dt    ,"','",
                      npts  ,"','",
                      md5,"','",
                      author,"')", sep=""
                      ))
dbDisconnect(con)
}